Automatically use CMakes 3.19 ISPC support for examples
ispc/ispc pull request #1931
Opened 2020-12-04 21:23 UTC by robertmaynard

2020-12-08 07:53 UTC, dbabokin commented
For broader review context I'm adding the list of commits to CMake, which add ISPC support enabled in this PR:
https://github.com/Kitware/CMake/commit/34cc6acc81758e29f8c88607c21ab11d8807f87c Add ISPC compiler support to CMake
https://github.com/Kitware/CMake/commit/e783bf8aa6f90ddb1458c7b1a78c5d0225c1496a ISPC: Support ISPC header generation byproducts and parallel builds
https://github.com/Kitware/CMake/commit/2368f46ba42efab00f7a0c7d1b24301f19196176 ISPC: Support building with the MSVC toolchain
https://github.com/Kitware/CMake/commit/8976817d6d4cf8ba5755ab24e2760c4c9cb485de ISPC: Update help documentation to include ISPC 
https://github.com/Kitware/CMake/commit/5a1750017e65727660167ae1953746a3fd3d2c7b ISPC: Add compiler launcher support
https://github.com/Kitware/CMake/commit/a020787a9b7ede3aa490345bd446e469fb1713d2 ISPC: Support generation for multiple instruction sets
https://github.com/Kitware/CMake/commit/c83711d9bd6f6fdbe534f475727bf80f7e8a8603 ISPC tests will now run on any hardware that only supports SSE2 
https://github.com/Kitware/CMake/commit/a83521e082f11fd08027e0f440408914bd83a5eb ISPC: Use the `obj` file extension for objects on windows
https://github.com/Kitware/CMake/commit/8de145cae18a8c368ffce60c511d6f6424c55aa2 ISPC: DynamicLibrary test now passes on windows.
https://github.com/Kitware/CMake/commit/bf88a94d88556ecd93e5612afe3fad99334579fb ISPC: CompilerLauncher tests work properly with x86 builds
https://github.com/Kitware/CMake/commit/e17e2c6a517cf40b41014cdf3e239c0b21da868e ISPC: CheckCompilerFlags and CheckSourceCompiles support ISPC

2020-12-09 01:05 UTC, aneshlya commented
Hi @robertmaynard,

Thanks a lot for your pull request, it looks great!
I'm worried a little bit about headers extensions change: "_ispc.h" to ".ispc.h". Historically in all our examples, guides and docs we recommended to use "_ispc.h" extension. I don't want to force people to update their source code with new header names if possible. Can the extension be changed to "_ispc.h"? Or can the header name be configurable from user's side?

2020-12-09 01:05 UTC, aneshlya requested changes

2020-12-09 01:37 UTC, aneshlya commented on examples/cmake/AddISPCExampleModern.cmake
> +    set(ISPC_KNOWN_TARGETS "sse2" "sse4" "avx1-" "avx2" "avx512knl" "avx512skx" "neon")
Is this line needed now?

2020-12-09 01:48 UTC, aneshlya commented
We also have GPU support in ISPC for which .spv and .zebin files are produced. You can see specific options/commands here: https://github.com/ispc/ispc/blob/master/ispcrt/cmake/ispc.cmake#L222. Would it be possible to support ISPC for GPU in cmake as well?

2020-12-09 04:59 UTC, pbrubaker commented
> Hi @robertmaynard,
> 
> Thanks a lot for your pull request, it looks great!
> I'm worried a little bit about headers extensions change: "_ispc.h" to ".ispc.h". Historically in all our examples, guides and docs we recommended to use "_ispc.h" extension. I don't want to force people to update their source code with new header names if possible. Can the extension be changed to "_ispc.h"? Or can the header name be configurable from user's side?

I have been using `.isph` as the extension for the vscode and VS extensions, and Embree uses it too.  https://www.embree.org/downloads.html

2020-12-09 14:57 UTC, robertmaynard commented on examples/cmake/AddISPCExampleModern.cmake
> +    set(ISPC_KNOWN_TARGETS "sse2" "sse4" "avx1-" "avx2" "avx512knl" "avx512skx" "neon")
No it isn't needed, I will drop it.

2020-12-09 15:02 UTC, robertmaynard commented on examples/cmake/AddISPCExampleModern.cmake
> +      target_compile_options(${example_NAME} PRIVATE $<$<COMPILE_LANGUAGE:C,CXX>:${arch_flag}>)
I intended to replace the manual usage of `--fpie` and `--pic` with CMake's `POSITION_INDEPENDENT_CODE` abstraction but didn't finish this as the tests built cleanly locally without any PIC flags.

I have corrected this, and now will build with PIC enabled.

2020-12-09 15:11 UTC, robertmaynard commented
> Hi @robertmaynard,
> 
> Thanks a lot for your pull request, it looks great!
> I'm worried a little bit about headers extensions change: "_ispc.h" to ".ispc.h". Historically in all our examples, guides and docs we recommended to use "_ispc.h" extension. I don't want to force people to update their source code with new header names if possible. Can the extension be changed to "_ispc.h"? Or can the header name be configurable from user's side?

Given that `_ispc.h` is the current recommended practise I can update CMake to use this pattern. I am not sure that we would want this to be user-configured at this point.

2020-12-09 15:13 UTC, robertmaynard commented
> We also have GPU support in ISPC for which .spv and .zebin files are produced. You can see specific options/commands here: https://github.com/ispc/ispc/blob/master/ispcrt/cmake/ispc.cmake#L222. Would it be possible to support ISPC for GPU in cmake as well?

This is something that could be covered by future collaboration between the ISPC and CMake's teams. I would be hestitant to add support right now, as I thought this feature was still experimental and the compiler byproducts/output are still subject to change.

2020-12-09 16:05 UTC, jeffamstutz commented
I think it is too early to jump to the conclusion that the current GPU output artifacts is the right approach for composing with CMake. I'd like to see GPU outputs (`.spv` and `.zebin` alike) end up as embedded binary data that is accessed via functions exported in a `_ispc.h` header first before making build systems more complicated.

2020-12-09 17:57 UTC, jeffamstutz commented
> I am not sure that we would want this to be user-configured at this point.

@robertmaynard what is the downside of providing something like `CMAKE_ISPC_HEADER_SUFFIX` to make generated header names configurable? I definitely understand wanting to minimize the number of points of configuration in any feature (that's reason enough to be hesitant here), but I'm just curious if there's something else too.

2020-12-09 17:59 UTC, aneshlya commented
I completely agree that we don't need to add GPU support to build system right now. Just wanted to ensure that you know that we have GPU support and we'll need CMake changes for that in the future.

2020-12-09 18:04 UTC, aneshlya commented
> Given that _ispc.h is the current recommended practise I can update CMake to use this pattern. I am not sure that we would want this to be user-configured at this point.

Looks like even in this pull request review we have different opinions about what extension should be. So it seems that to have it configurable will be quite useful. @dbabokin, what do you think?

2020-12-09 18:09 UTC, aneshlya commented on examples/cmake/AddISPCExampleModern.cmake
> +      target_compile_options(${example_NAME} PRIVATE $<$<COMPILE_LANGUAGE:C,CXX>:${arch_flag}>)
Thanks! Works without any issues on my system.

2020-12-09 18:41 UTC, aneshlya approved these changes

2020-12-09 20:43 UTC, robertmaynard commented
>  what is the downside of providing something like CMAKE_ISPC_HEADER_SUFFIX to make generated header names configurable? I definitely understand wanting to minimize the number of points of configuration in any feature (that's reason enough to be hesitant here), but I'm just curious if there's something else too.

It is partially about the nubmer of configuration points, and also making sure we have captured the necessary requirements.
My initial thought was we could go with a hard-coded "_ispc.h" but I agree it something like `CMAKE_ISPC_HEADER_SUFFIX` would be the better approach.

Since we want to capture the "_ispc.h" the algorithm for `CMAKE_ISPC_HEADER_SUFFIX` would be to take the input source file ( `example.ispc` ) and drop the right-most extension plus `.`, and replace it with `CMAKE_ISPC_HEADER_SUFFIX`. 

This would produce the following transformations:

| CMAKE_ISPC_HEADER_SUFFIX  | input | output |
| ------------- | ------------- | ------------- |
| "_ispc.h"  | simple.ispc  | simple_ispc.h |
| "_ispc.h"  | simple.ispc  | simple_ispc.h |
| ".ispch"  |  simple.ispc  | simple.ispch |

Note: Should we drop only the right most extension or drop all extensions? I think we want only to drop the right most as the transformation of `complicated.ver1.ispc` into `complicated_ispc.h` could clobber headers generated by `complicated.ver2.ispc`

2020-12-09 21:09 UTC, jeffamstutz commented
I agree that dropping the right-most extension is what makes the most intuitive sense and is the most robust/future-proof.

2020-12-09 21:10 UTC, jeffamstutz commented
I would think for compatibility with CMake 3.19.1, `CMAKE_ISPC_HEADER_SUFFIX` would default to `".ispc.h"`?

2020-12-09 21:21 UTC, robertmaynard commented
> I would think for compatibility with CMake 3.19.1, `CMAKE_ISPC_HEADER_SUFFIX` would default to `".ispc.h"`...or is a breaking changing between 3.19.1 and 3.19.2 for this not a big deal?
> 
> FWIW, defaulting to `".ispc.h"` makes sense to me.

Luckily since ISPC was introduced in CMake 3.19 we can break 3.19.0 and 3.19.1 without issue. Personally getting the right defaults now, are worth the very short term pain caused by the breakage.

2020-12-09 23:35 UTC, dbabokin commented
@pbrubaker I think there's some confusion here. `*.isph` is an ISPC header file, which compliments `*.ispc` files and contains ISPC code, i.e. they are included by `*.ispc` files. While `*.ispc.h` / `*_ispc.h` in question are generated C/C++ interoperability headers (contain C/C++ code).

2020-12-09 23:45 UTC, pbrubaker commented
Yeah, I figured out my mistake, sorry for detailing.

> On Dec 9, 2020, at 3:35 PM, Dmitry Babokin <notifications@github.com> wrote:
> 
> ﻿
> @pbrubaker I think there's some confusion here. *.isph is an ISPC header file, which compliments *.ispc files and contains ISPC code, i.e. they are included by *.ispc files. While *.ispc.h / *_ispc.h in question are generated C/C++ interoperability headers (contain C/C++ code).
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-10 00:21 UTC, dbabokin commented
For the choice between `*_ispc.h` and `*.ispc.h` - it's difficult one, as it's really a matter of taste. Some people tend to name files with multiple dots, while others avoid it by using underscore.

I would vote for underscore as a default and making it configurable. Mostly because this is the way we advertise this pattern for a long time and hence this is the way how people are already using it.

2020-12-10 22:23 UTC, robertmaynard commented
> For the choice between `*_ispc.h` and `*.ispc.h` - it's difficult one, as it's really a matter of taste. Some people tend to name files with multiple dots, while others avoid it by using underscore.
> 
> I would vote for underscore as a default and making it configurable. Mostly because this is the way we advertise this pattern for a long time and hence this is the way how people are already using it.

I have opened a merge request that changes the default header suffix to be `_ispc.h` and also provides a configuration point.
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5597

2020-12-11 01:09 UTC, dbabokin commented
@robertmaynard Do you know when the next minor update for CMake 3.19 is coming?

2020-12-11 13:18 UTC, robertmaynard commented
> @robertmaynard Do you know when the next minor update for CMake 3.19 is coming?

There is a collection of regressions queued up for 3.19.2, and once they are resolved we should release. I can't give a firm date, but it will be 'soon'.

2020-12-11 23:00 UTC, dbabokin commented
This sounds good. 

Can we use `3.19.2` in `CMAKE_VERSION VERSION_GREATER_EQUAL 3.19` or it can be only `3.19`?

I suggest changing this PR to match your changes in CMake and merge it.

2020-12-14 14:16 UTC, robertmaynard commented
> This sounds good.
> 
> Can we use `3.19.2` in `CMAKE_VERSION VERSION_GREATER_EQUAL 3.19` or it can be only `3.19`?
> 
> I suggest changing this PR to match your changes in CMake and merge it.

I have updated to activate only on `3.19.2`. I would like to be safe and hold off on merging this till 3.19.2 is released just in case something goes wrong and we need to yank the ISPC changes.

2020-12-14 20:09 UTC, dbabokin commented
Sounds good for waiting till 13.19.2 is released.

Should we also roll back the changes in convert `_ispc.h` to `.ispc.h` in this PR?

Also I think we need a CI pipeline, which would test CMake 3.19.2 or later. Either @kraszkow or I will take care about it, once it's released.

2020-12-14 20:35 UTC, robertmaynard commented
> Should we also roll back the changes in convert `_ispc.h` to `.ispc.h` in this PR?

I have rolled back to using `_ispc.h`

2020-12-17 21:30 UTC, dbabokin commented
`3.19.2` is out. I gave it a try and it fail to build examples with ISPC ([log](https://github.com/dbabokin/ispc/runs/1573066422?check_suite_focus=true)):
```
-- The ISPC compiler identification is unknown
CMake Error at examples/cmake/AddISPCExample.cmake:77 (enable_language):
  No CMAKE_ISPC_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "ISPC" or the CMake cache entry CMAKE_ISPC_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  examples/CMakeLists.txt:41 (include)


-- Configuring incomplete, errors occurred!
```

Which is kind of expected... As if we are trying to find ISPC, when we are configuring ISPC build, it's obviously cannot be found... Any ideas how to handle it gracefully?

2020-12-18 15:55 UTC, robertmaynard commented
> `3.19.2` is out. I gave it a try and it fail to build examples with ISPC ([log](https://github.com/dbabokin/ispc/runs/1573066422?check_suite_focus=true)):
> 
> ```
> -- The ISPC compiler identification is unknown
> CMake Error at examples/cmake/AddISPCExample.cmake:77 (enable_language):
>   No CMAKE_ISPC_COMPILER could be found.
> 
>   Tell CMake where to find the compiler by setting either the environment
>   variable "ISPC" or the CMake cache entry CMAKE_ISPC_COMPILER to the full
>   path to the compiler, or to the compiler name if it is in the PATH.
> Call Stack (most recent call first):
>   examples/CMakeLists.txt:41 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> ```
> 
> Which is kind of expected... As if we are trying to find ISPC, when we are configuring ISPC build, it's obviously cannot be found... Any ideas how to handle it gracefully?

Yes we are caught in a chicken and egg problem, as CMake expects that compiler to exist before it is executed.

A couple of thoughts come to mind:
1. We could use the Legacy fallback mode when building ISPC itself. This doesn't allow ISPC to leverage the new feature, but when packaged users will be able too.
2. We could do a fancier version of above, but where if you re-run CMake after you have built the ISPC executable the examples will detect that and switch over to the `Modern` path. This will require some additional changes as we will need to make sure that all the examples depend on the `ISPC` target so they aren't built before the executable on subsequent build invocations.

2020-12-18 16:42 UTC, jeffamstutz commented
One option is to use `ExternalProject` to do a unique CMake invocation on examples that executes only after the build of ISPC itself. This would lend itself to the examples being written as a stand-alone CMake build, and invoking them as a part of building ISPC itself is then only one way of building them.

@robertmaynard what do you think?

2020-12-18 16:49 UTC, robertmaynard commented
> One option is to use `ExternalProject` to do a unique CMake invocation on examples that executes only after the build of ISPC itself. This would lend itself to the examples being written as a stand alone CMake build, and invoking them as a part of building ISPC itself is then only one way of building them.
> 
> @robertmaynard what do you think?

I prefer this approach now that you bring it up, as it creates an excellent separation of the two components ( ISPC the compiler, and the ISPC examples ).

2020-12-20 08:16 UTC, dbabokin commented
> I prefer this approach now that you bring it up, as it creates excellent separation of the two components ( ISPC the compiler, and the ISPC examples ).

I agree, this is the way!

2020-12-23 18:22 UTC, robertmaynard commented
I have refactored `examples` and `examples_genx` to use ExternalProject so we can properly use the ISPC compiler we just built.

2020-12-29 08:46 UTC, dbabokin requested changes
`examples/cmake/*` files use mix of 2 and 4 indentation, style need to be more consistent. In ISPC we typically use 4 spaces indentation.

2020-12-29 08:46 UTC, dbabokin commented on CMakeLists.txt
> +if ( ISPC_INCLUDE_EXAMPLES AND NOT ISPC_PREPARE_PACKAGE)
```suggestion
if (ISPC_INCLUDE_EXAMPLES AND NOT ISPC_PREPARE_PACKAGE)
```

2020-12-29 08:46 UTC, dbabokin commented on CMakeLists.txt
> +            -DISPC_EXECUTABLE:PATH=$<TARGET_FILE:ispc>
```suggestion
            -DISPC_EXECUTABLE:PATH=$<TARGET_FILE:ispc>
            -DCMAKE_C_COMPILER:PATH=${CMAKE_C_COMPILER}
            -DCMAKE_CXX_COMPILER:PATH=${CMAKE_CXX_COMPILER}
```

By default we should use clang used for ISPC build.

2020-12-29 08:46 UTC, dbabokin commented on CMakeLists.txt
> +            -DISPC_EXECUTABLE:PATH=$<TARGET_FILE:ispc>
```suggestion
            -DISPC_EXECUTABLE:PATH=$<TARGET_FILE:ispc>
            -DCMAKE_C_COMPILER:PATH=${CMAKE_C_COMPILER}
            -DCMAKE_CXX_COMPILER:PATH=${CMAKE_CXX_COMPILER}
```

2020-12-29 08:46 UTC, dbabokin commented on examples/CMakeLists.txt
```suggestion

if(CMAKE_BUILD_TYPE)
    # Validate build type
    set(CONFIGURATION_TYPES "Debug;Release;RelWithDebInfo")

    string(FIND "${CONFIGURATION_TYPES}" "${CMAKE_BUILD_TYPE}" MATCHED_CONFIG)
    if (${MATCHED_CONFIG} EQUAL -1)
         message(FATAL_ERROR "CMAKE_BUILD_TYPE (${CMAKE_BUILD_TYPE}) allows only the following values: ${CONFIGURATION_TYPES}")
    endif()
else(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE "Release")
    message(STATUS "Build type not specified: Use Release by default.")
endif(CMAKE_BUILD_TYPE)

```

Another side effect of moving examples to external project is loosing default build type, while it's critical to build as `Release` by default, as its used for performance evaluation. This is copy-paste of ISPC CMakeLists.txt.

2020-12-29 14:34 UTC, robertmaynard commented
> `examples/cmake/*` files use mix of 2 and 4 indentation, style need to be more consistent. In ISPC we typically use 4 spaces indentation.

I believe I corrected everything to 4 space identation, and have included all your suggested fixes

2020-12-29 22:31 UTC, dbabokin approved these changes

2020-12-29 23:48 UTC, merged

2020-12-29 23:49 UTC, dbabokin commented
@robertmaynard Thank you for the contribution!