builtins: align all implementations of __round_varying
ispc/ispc pull request #2793
Opened 2024-03-13 17:32 UTC by nurmukhametov

Make all implementations of __round_varying across different targets and types to actually do roundeven.

This PR fixes #2780

2024-03-13 22:09 UTC, aneshlya approved these changes
Looks good!

2024-03-13 23:09 UTC, dbabokin requested changes
Why `@llvm.roundeven`, but not `@llvm.round`?

2024-03-14 13:16 UTC, nurmukhametov commented
> Why `@llvm.roundeven`, but not `@llvm.round`?

I suggest that this is the actual semantic of ISPC `round` stdlib function. The reason I think so because of its implementation for other targets https://github.com/ispc/ispc/blob/71f6866107da93bb963e9e1a5d2313df493a7ce5/builtins/target-sse4-common.ll#L22 https://github.com/ispc/ispc/blob/71f6866107da93bb963e9e1a5d2313df493a7ce5/builtins/target-sse4-i32x4.ll#L100 https://github.com/ispc/ispc/blob/71f6866107da93bb963e9e1a5d2313df493a7ce5/builtins/target-avx-common-8.ll#L92

2024-03-15 04:47 UTC, dbabokin commented
My understanding of the rounding functions (and other math lib functions, actually) design in ISPC math library is to be close to C versions of the same routines. There's no point to give them any other definitions, at least I don't see such reasons.

Otherwise it's just confuses people. Especially as we don't give strict definition of these functions.

2024-03-16 01:39 UTC, dbabokin commented
Ok, looks like I start to understand what's going on.

x86 has just 4 rounding modes ([link](https://xem.github.io/minix86/manual/intel-x86-and-64-manual-vol2/o_b5573232dd8f1481-1245.html)). These 4 modes correspond to `ceil`, `floor`, `trunk`, and `roundeven`.

`round` and `roundeven` are not much different. `round` rounds `x.5` to `x+1` for positive numbers, while `roundeven` rounding depends on `x` being odd or even. So numerically is not much different and the difference will not matter for many cases.

Original implementation is indeed uses `roundeven` mode and is a single x86 instruction - but this is mostly for efficiency, as it directly maps to single hardware instruction. Though it difficult to say for sure, I was not involved in original implementation and I can only guess.

`nearbyint` appeared originally in AVX512 implementation. This implementation was done by an intern and I probably didn't catch that.

`nearbyint` uses dynamic rounding and should be avoided for `round` implementation for sure.

Some historical background on LLVM support for rounding intrinsics
LLVM 3.3 (June 2013): `ceil`/`floor/`trunk`/`rint`/`nearbyint` were added.
LLVM 3.4 (January 2014): `round` was added.
LLVM 11.0 (October 2020): `roundeven` was added.

> I couldn't manage to find any round implementation that matches C math round function.

It's [@llvm.round.*](https://llvm.org/docs/LangRef.html#llvm-round-intrinsic), it specifically defined as "This function returns the same values as the libm round functions would, and handles error conditions in the same way."

> It is confusing right now.

Yes, that's the problem and that's what we are trying to fix :)

Given all this background, I still don't know what's the best way to proceed.
1. use `@llvm.round.*` uniformly. Pro: it's fully compliant with libm. Cons: implementation is 4 instructions and it might break some code.
2. use `@llvm.roundeven.*` uniformly. Pro: don't break existing code (except when switching from `nearbyint`), more efficient on x86. Cons: will not fully comply with libm definition.

I'm slightly leaning towards 2, which is current patch is. Though documenting that behavior is needed, I think.

2024-03-18 12:44 UTC, nurmukhametov commented
> > I couldn't manage to find any round implementation that matches C math round function.
> 
> It's [@llvm.round.*](https://llvm.org/docs/LangRef.html#llvm-round-intrinsic), it specifically defined as "This function returns the same values as the libm round functions would, and handles error conditions in the same way."

I meant ISPC round implementation that matches C math round.

> Given all this background, I still don't know what's the best way to proceed.
> 
> 1. use `@llvm.round.*` uniformly. Pro: it's fully compliant with libm. Cons: implementation is 4 instructions and it might break some code.
> 2. use `@llvm.roundeven.*` uniformly. Pro: don't break existing code (except when switching from `nearbyint`), more efficient on x86. Cons: will not fully comply with libm definition.
> 
> I'm slightly leaning towards 2, which is current patch is. Though documenting that behavior is needed, I think.

I'm sure that the second option is the only reasonable one. The ISPC documentation doesn't mention any math compliancy to `libm` C functions. It actually makes a quite opposite statement:

> Standard rounding functions are provided for float16, float and double types. (On machines that support Intel®SSE or Intel® AVX, these functions all map to variants of the roundss and roundps instructions, respectively.)

2024-03-18 17:56 UTC, dbabokin commented
Another option is to use `@llvm.round.*` for `round()` implementation and introduce `roundeven()` and document the semantics and add recommendations to use them with respect to performance expectations.

The idea is that we don't only need to comply with current documentation, which is sometimes vague and incomplete. But rather to define our vision for the solution that we'd like to have and move towards that. Over the years we definitely saw the demand for more strictly defined and portable math lib and complying with libm definitions is probably the best way to provide intuitive semantics.

2024-03-18 18:04 UTC, nurmukhametov commented
> Another option is to use `@llvm.round.*` for `round()` implementation and introduce `roundeven()` and document the semantics and add recommendations to use them with respect to performance expectations.
> 

But it breaks correctness (the expected result) of the legacy code.

2024-03-18 18:24 UTC, dbabokin commented
> But it breaks correctness (the expected result) of the legacy code.

It could break potentially. We should document that in release notes. We should check with big customers that we know to see the impact if we decide to go this path.

But if the impact on existing code is low, then benefits of having cleaner definition outweighs it.

2024-03-26 19:11 UTC, aneshlya commented
I think we should proceed with `roundeven` and explicitly state in the documentation that ISPC's `round` function aligns with `roundeven` + describe rationale behind it (direct mapping to a single x86 instruction, offering enhanced performance — a core objective of ISPC).
Current docs have some mentions about it but very implicit: `On machines that support Intel®SSE or Intel® AVX, these functions all map to variants of the ``roundss`` and ``roundps`` instructions, respectively.`

I believe that there is no need to introduce one more rounding function unless one of "big customers" requests it.

2024-03-27 02:53 UTC, dbabokin approved these changes
I'm ok with Arina's suggestion. Note, that docs needs clarification.

2024-03-27 14:29 UTC, nurmukhametov commented
I've rebased the branch and updated docs.

2024-03-27 16:05 UTC, aneshlya approved these changes

2024-03-27 16:09 UTC, aneshlya commented
One lit test requires update on Windows.

2024-03-28 19:49 UTC, merged