WIP: Remove no spr dispatch
ispc/ispc pull request #2810
Opened 2024-03-25 19:47 UTC by nurmukhametov

2024-03-26 18:38 UTC, aneshlya approved these changes
LGTM

2024-03-27 03:27 UTC, dbabokin requested changes
These are scary changes (to me), that's why I did some unification of this code over the years, but never went all the way to making dispatch compiled during the build. So I applaud your courage here :)

My only concern (beyond that it's not fully working for non-x86 builds for now) is that it's completely missing test coverage. When I was updating dispatch, I was manually verifying the changes - looking at the resulting code and running under SDE to check that it correctly behaves under all different conditions.

Current testing infra is not designed to support such testing. I suggest adding new class of tests. Something like "integrations tests" and try multi-target under SDE with all conditions that are interesting for us. Probably it should be just hardcoded via the script. 

Also probably some other tests will need to be added to this class - for example ABI (C <->ISPC) testing and some of the runtime tests that you were trying to add to lit tests.

2024-03-27 03:27 UTC, dbabokin commented on cmake/GenerateBuiltins.cmake
> +        COMMAND ${CLANGPP_EXECUTABLE} -x c ${ISPC_OPAQUE_FLAGS} ${DISP_TYPE} -march=x86-64 -mtune=generic -O2 -emit-llvm -S -c ${inputFilePath} -o -
I have this error on ARM macOS without cross-build enabled:
```
[  5%] Generating builtins-dispatch-macos.cpp
clang++: error: unsupported argument 'x86-64' to option '-march='
[  7%] Generating builtins-dispatch.cpp
clang++: error: unsupported argument 'x86-64' to option '-march='
```
which is not surprising.

Also, looks like we are missing ARM builds in CI. We do have hosted ARM Linux runner, we should enabled a ARM-only and full ARM build there. We used to have Travis to test ARM, but it's not running anymore, I'm not sure what happened to it.

2024-03-27 12:58 UTC, nurmukhametov commented
OK, then reduce the scope of this PR to just removing `dispatch-no-spr.ll`. 

I created issues about everything else #2815, #2816, #2817 .

2024-03-27 20:56 UTC, dbabokin approved these changes
LGTM

2024-03-28 14:37 UTC, merged