A small clean up
ispc/ispc pull request #2843
Opened 2024-04-29 11:18 UTC by nurmukhametov

This PS deletes a few functions that are not used in the project. It also deletes most of `#if 0` code (either debug or commented out since the beginning).

It also updates upload actions that left unupdated since https://github.com/ispc/ispc/pull/2820

2024-04-29 18:29 UTC, dbabokin requested changes

2024-04-30 02:59 UTC, turinevgeny approved these changes

2024-04-30 14:06 UTC, nurmukhametov commented on src/sym.cpp
> -    return closestTypeMatch(str, false);
Yes, indeed. Fixed and test was added.

2024-04-30 16:20 UTC, dbabokin commented on src/sym.cpp
> -    return closestTypeMatch(str, false);
Probably it's better to just make it work for non-enums :) But it's up to you. If you'd like to proceed with current fix, please remove mentioning of `structsVsEnums` in the comments and you are good to go.

2024-05-02 10:14 UTC, nurmukhametov commented on src/sym.cpp
> -    return closestTypeMatch(str, false);
Hm, I don't understand which example should trigger the corresponding warnings for structs. I tried to create something but I did only manage to get several crashes. See the issue https://github.com/ispc/ispc/issues/2844 . So, I think it is better to fix separately.

2024-05-02 17:04 UTC, dbabokin approved these changes
LGTM

2024-05-02 18:16 UTC, merged