Remove unused CI jobs
ispc/ispc pull request #2887
Opened 2024-06-14 14:03 UTC by nurmukhametov

This PR removes unused CI jobs and related configuration files:

1. calcite configuration
2. Travis job
3. `ispc-svml` it doesn't look any different from the jobs that we run in `ispc-ci`.

2024-06-17 09:14 UTC, dbabokin requested changes
I don't really like removing svml job. It's useful. Iwould suggest updateing it to the working state and make it run weekly.

Otherwise SVML support will get broken again.

2024-06-17 10:31 UTC, nurmukhametov commented
I am ready to update it but explain how it is different from the jobs in `ispc-ci.yml` that use `svml`.

2024-06-18 20:40 UTC, dbabokin approved these changes
LGTM

2024-06-24 22:41 UTC, aneshlya approved these changes

2024-06-25 14:52 UTC, merged