Add -ffunction-sections flag
ispc/ispc pull request #2997
Opened 2024-09-11 18:56 UTC by nurmukhametov

It forces the compiler to place each function in its own section.

This PR addresses the issue #2902. One can eliminate unused copies of exported functions providing this flag and enabling a linker flag that removes unused sections (`-gc-sections` for `ld` and compatible linkers).

2024-09-11 19:26 UTC, aneshlya commented on src/main.cpp
> +    printf("    [-ffunction-sections]\t\t\tPlace each function in its own section\n");
Maybe 
```suggestion
    printf("    [-f[no]function-sections]\t\t\tPlace each function in its own section\n");
```

2024-09-11 19:29 UTC, aneshlya approved these changes
Looks good!

2024-09-12 17:09 UTC, nurmukhametov commented on src/main.cpp
> +    printf("    [-ffunction-sections]\t\t\tPlace each function in its own section\n");
Done

2024-09-13 03:56 UTC, dbabokin requested changes
The changes don't work on macOS - the function is still in TEXT section.

But I tried clang and had the same behavior, i.e. no effect on emitted assembler. Do you know why? It's probably ok to have the same behavior as clang (i.e. accept the option which has no effect), but would be good to understand what's going on.

2024-09-13 03:56 UTC, dbabokin commented on src/main.cpp
> +    printf("    [-f[no-]function-sections]\t\t\tPlace each function in its own section\n");
```suggestion
    printf("    [-f[no-]function-sections]\t\tPlace each function in its own section\n");
```

2024-09-13 11:18 UTC, nurmukhametov commented
> The changes don't work on macOS - the function is still in TEXT section.
> 
> But I tried clang and had the same behavior, i.e. no effect on emitted assembler. Do you know why? It's probably ok to have the same behavior as clang (i.e. accept the option which has no effect), but would be good to understand what's going on.

Yes. It looks like a specific mechanism is slightly different with macOS toolchain. Although, I didn't manage to find quickly what it is. Anyway, the usage of `-dead_strip` linker option ([docs](https://github.com/llvm/llvm-project/blob/9cd93774098c861c260090a690f428b7ae031c65/clang/include/clang/Basic/AttrDocs.td#L83)) eliminates unused copies regardless of `-ffunction-sections` flag.

2024-09-13 11:25 UTC, nurmukhametov commented on src/main.cpp
> +    printf("    [-f[no-]function-sections]\t\t\tPlace each function in its own section\n");
Done

2024-09-13 17:26 UTC, dbabokin approved these changes
Could you put this knowledge about macOS (that it doesn't work in the same way on macOS, that symbols are stripped anyway, and that we are following clang, which does have this option on macOS, but it does nothing) to comments in the test?

After that it's good to merge.

2024-09-16 13:37 UTC, nurmukhametov commented
> Could you put this knowledge about macOS (that it doesn't work in the same way on macOS, that symbols are stripped anyway, and that we are following clang, which does have this option on macOS, but it does nothing) to comments in the test?
> 
> After that it's good to merge.

I have added this comment and updated docs.

2024-09-16 16:20 UTC, dbabokin commented on docs/ispc.rst
> +for ``MSVC link.exe``. On macOS, this flag does not have any effect (as clang)
```suggestion
for ``MSVC link.exe``. On macOS, this flag does not have any effect (as in clang)
```

2024-09-17 12:15 UTC, merged