Migrate appveyor jobs to Github Actions
ispc/ispc pull request #3118
Opened 2024-11-20 20:00 UTC by nurmukhametov

This relates to #2966.

2024-11-21 18:57 UTC, aneshlya commented
Great that jobs are passing!
But I think it can be combined with the jobs from ispc-ci.
So it seems that it does 3 things:
1. Wasm-enabled build (win and linux)
2. ISPC_CROSS=ON (win and lin) - this should be enabled for the builds in ispc-ci at least in "release" jobs.
3. Benchmarks running (not related to wasm, win only) - can be part of full nightly testing
4. Examples running (not related to wasm, win only) - can be part of full nightly testing

2024-11-24 14:53 UTC, dbabokin reviewed
I'm not sure that we need to introduce one more build workflow, which just "Ex Appveyor".

The key reason for Appveyor was to have the latest build available to public download. This was the build with all targets enabled (including WASM). So enabling uploading artifacts to the single permanent location is the key for porting Appveyor workflow to Github Actions. I think this can be done as part of `ispc-ci` workflow.

To enable permanent upload location we can have a "pre-release" on Github called "latest" (or something like that) and push there for the builds in `ispc/ispc` repo when pushed to `main`.

2025-01-16 16:15 UTC, nurmukhametov commented
As requested, this PR now adds ex-AppVeyor jobs inside ISPC-CI and creates a separate workflow to build and publish trunk artifacts to GitHub pre-release. See an example job: https://github.com/nurmukhametov/ispc/actions/runs/12810517014 pre-release: https://github.com/nurmukhametov/ispc/releases/tag/trunk-artifacts

2025-01-16 17:48 UTC, aneshlya requested changes

2025-01-16 17:48 UTC, aneshlya commented on .github/workflows/ispc-ci.yml
> +        python scripts\perf.py -n 1 -g "Visual Studio 16" && ^
This command builds and runs examples and it's not related to wasm build anyhow. I would move it from here to another job (probably <os>-build-examples is the best one). I think running perf.py on Linux also makes sense.

2025-01-16 17:48 UTC, aneshlya commented on .github/workflows/trunk-artifacts.yml
> +        cmake -B build ./ -DISPC_PREPARE_PACKAGE=ON -DCMAKE_INSTALL_PREFIX="$ISPC_HOME"/install -DISPC_CROSS=ON -DWASM_ENABLED=ON -DCMAKE_CXX_FLAGS="-Werror"
I think we should run here the command closest to our release packages (from linux-build-ispc-llvm18-release job?). Same for Windows.

2025-01-16 17:48 UTC, aneshlya commented on .github/workflows/trunk-artifacts.yml
> +
Please add concurrency group to prevent parallel releases
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

2025-01-16 17:48 UTC, aneshlya commented on .github/workflows/trunk-artifacts.yml
> +        tag_name: trunk-artifacts
Maybe use tag_name "main"?

2025-01-17 12:32 UTC, nurmukhametov commented on .github/workflows/trunk-artifacts.yml
> +        tag_name: trunk-artifacts
I am not sure that having a tag name (it is just a usual git tag) the same as the branch name is a good idea. What about `main-artifacts`, `main-binaries`, `main-archives`, or `main-pre-release`?

2025-01-17 17:47 UTC, nurmukhametov commented on .github/workflows/trunk-artifacts.yml
> +
Done

2025-01-17 17:47 UTC, nurmukhametov commented on .github/workflows/trunk-artifacts.yml
> +        cmake -B build ./ -DISPC_PREPARE_PACKAGE=ON -DCMAKE_INSTALL_PREFIX="$ISPC_HOME"/install -DISPC_CROSS=ON -DWASM_ENABLED=ON -DCMAKE_CXX_FLAGS="-Werror"
I have fixed it

2025-01-17 17:47 UTC, nurmukhametov commented on .github/workflows/ispc-ci.yml
> +        python scripts\perf.py -n 1 -g "Visual Studio 16" && ^
Done

2025-01-17 17:55 UTC, aneshlya commented on .github/workflows/trunk-artifacts.yml
> +        tag_name: trunk-artifacts
`main-artifacts` is fine. What I'd like to make clear here is that it is latest binaries built from the main branch.

2025-01-17 21:28 UTC, aneshlya approved these changes
Looks good to me. Maybe @dbabokin may comment more since he has experience with publishing pre-release artifacts.

2025-01-22 06:57 UTC, dbabokin approved these changes
Looks good to me.

2025-01-22 14:04 UTC, merged